package com.huole.learn.mapper;

import com.huole.learn.entity.ParsingInfoDO;
import com.huole.learn.entity.ParsingInfoParam;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ParsingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parsing_info
     *
     * @mbggenerated Sat Aug 03 18:38:16 CST 2024
     */
    int countByExample(ParsingInfoParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parsing_info
     *
     * @mbggenerated Sat Aug 03 18:38:16 CST 2024
     */
    int deleteByExample(ParsingInfoParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parsing_info
     *
     * @mbggenerated Sat Aug 03 18:38:16 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parsing_info
     *
     * @mbggenerated Sat Aug 03 18:38:16 CST 2024
     */
    int insert(ParsingInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parsing_info
     *
     * @mbggenerated Sat Aug 03 18:38:16 CST 2024
     */
    int insertSelective(ParsingInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parsing_info
     *
     * @mbggenerated Sat Aug 03 18:38:16 CST 2024
     */
    List<ParsingInfoDO> selectByExample(ParsingInfoParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parsing_info
     *
     * @mbggenerated Sat Aug 03 18:38:16 CST 2024
     */
    ParsingInfoDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parsing_info
     *
     * @mbggenerated Sat Aug 03 18:38:16 CST 2024
     */
    int updateByExampleSelective(@Param("record") ParsingInfoDO record, @Param("example") ParsingInfoParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parsing_info
     *
     * @mbggenerated Sat Aug 03 18:38:16 CST 2024
     */
    int updateByExample(@Param("record") ParsingInfoDO record, @Param("example") ParsingInfoParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parsing_info
     *
     * @mbggenerated Sat Aug 03 18:38:16 CST 2024
     */
    int updateByPrimaryKeySelective(ParsingInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parsing_info
     *
     * @mbggenerated Sat Aug 03 18:38:16 CST 2024
     */
    int updateByPrimaryKey(ParsingInfoDO record);
}